version: 1.0
services:
  postgres:
    image: postgres:lastest
    command: postgres -c 'max_connections=1000'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dbo
      POSTGRES_PASSWORD: 123456
    ports:
      - '5434:5432'
